version: 1.2
workflows:
  - name: ctat_mutations
    subclass: WDL
    publish: True
    primaryDescriptorPath: /WDL/Terra/ctat_mutations.Terra.hg38.wdl
    testParameterFiles:
      - /WDL/ctat_mutations.terra_inputs.json
    filters: # All tags, no branches
      branches:
        - master
